/** Korte uitleg bij begrippen in de app, getoond via <Tip k="…" />. Eén plek zodat de uitleg overal gelijk is. */
export const GLOSSARY = {
  // Handicap (WHS)
  index: "Je handicapindex volgens het World Handicap System: het gemiddelde van je beste 8 score differentials uit de laatste 20 qualifying rondes (bij minder rondes een kleiner aantal met correctie). Door de app berekend, dus indicatief.",
  official: "De index die de NGF officieel voor je heeft vastgelegd. Vul je in bij Instellingen; de app gebruikt hem als startpunt zolang er te weinig eigen rondes zijn.",
  lowIndex: "Je laagste index van de afgelopen 12 maanden. Is het ijkpunt voor de soft en hard cap, die voorkomen dat je index te snel stijgt.",
  differential: "Hoe goed een ronde was, omgerekend naar een baan van gemiddelde moeilijkheid: 113 ÷ slope × (AGS − course rating − PCC). Lager is beter.",
  ags: "Adjusted gross score: je bruto score, maar per hole maximaal een netto double bogey (par + 2 + je ontvangen slagen). Zo telt één rampzalige hole niet te zwaar.",
  pcc: "Playing conditions calculation: correctie als de omstandigheden die dag uitzonderlijk zwaar of makkelijk waren (−1 tot +3). Staat standaard op 0.",
  cap: "Soft cap: stijgt je index meer dan 3,0 boven je laagste index van 12 maanden, dan telt het deel daarboven maar voor de helft. Hard cap: nooit meer dan 5,0 stijging.",
  exceptional: "Uitzonderlijke score: een differential van 7 of meer onder je index. Dan gaan je recente differentials 1 omlaag (bij 10 of meer: 2).",
  nineHole: "Een 9-holes ronde wordt aangevuld tot 18 holes met de verwachte score voor de andere negen (op basis van je index), zodat hij als volledige differential meetelt.",
  best: "Van je laatste 20 differentials tellen alleen de beste (bij 20 rondes: 8) voor je index. Die zijn groen gemarkeerd.",
  qualifying: "Een ronde die meetelt voor je handicap: vooraf aangemeld en volgens de regels gespeeld. In Hole19 herken je dat aan het HCP-label. Niet-qualifying rondes tellen wel mee voor je statistieken.",
  allQualifying: "Wat je index zou zijn als ook je niet-qualifying rondes hadden meegeteld. Handig om te zien of je oefenrondes beter of slechter zijn dan je qualifying rondes.",
  whatToScore: "De score die je op deze tee minimaal moet halen om je index te laten dalen, gegeven je huidige laatste 20 rondes.",
  ch: "Course handicap: het aantal slagen dat je op deze baan en tee krijgt: index × slope ÷ 113 + (course rating − par).",
  ph: "Playing handicap: je course handicap × de allowance van de speelvorm (meestal 95%). Hiermee worden je slagen per hole en je punten bepaald.",
  hcpTriple: "Index vóór deze ronde / course handicap / playing handicap. Alle drie berekend uit je eigen rondes in de app, niet van de kaart.",
  allowance: "Welk percentage van je course handicap je als playing handicap krijgt. Standaard 95% voor individuele strokeplay en stableford.",
  startIndex: "De index waarmee de app rekent zolang je nog minder dan 3 rondes met rating en slope hebt. Leeg laten = je officiële NGF-index.",
  cardPh: "De playing handicap die op de kaart of in Hole19 staat. Wordt alleen gebruikt om te controleren of de punten goed zijn uitgelezen; de app rekent zelf met de handicap uit de database.",
  indexFromDb: "Je index op de datum van deze ronde, berekend uit je eigen rondes ervoor. Niet de handicap van de kaart.",

  // Baan
  cr: "Course rating: de score die een scratchspeler (handicap 0) gemiddeld haalt op deze tee. Ligt meestal rond de par.",
  slope: "Slope rating: hoeveel moeilijker de baan is voor een bogeyspeler dan voor een scratchspeler. Van 55 tot 155; 113 is gemiddeld.",
  si: "Stroke index: de moeilijkheidsvolgorde van de holes (1 = moeilijkst). Bepaalt op welke holes je je handicapslagen krijgt.",
  par: "Het aantal slagen dat een goede speler nodig heeft voor de hole: twee putts plus de slagen om de green te bereiken.",
  length: "Afstand van de tee tot de green, in meters.",
  loop: "Een lus van 9 holes. Twee lussen samen vormen een 18-holes combinatie.",
  combination: "Twee lussen samen als 18-holes baan, met een eigen stroke index over alle 18 holes.",
  tee: "De afslagplaats (kleur). Per tee en geslacht gelden een eigen course rating, slope en lengtes.",
  validFrom: "Vanaf deze datum geldt deze rating. Oudere rondes houden de rating die op dat moment gold.",
  teeGender: "Heren en dames hebben op dezelfde tee een andere course rating en slope.",

  // Score en statistieken
  gross: "Het totaal aantal slagen, zonder aftrek van handicap.",
  toPar: "Je bruto score min de par van de baan. +10 betekent tien slagen boven par.",
  points: "Stablefordpunten per hole: 2 voor netto par, 3 voor netto birdie, 1 voor netto bogey, 0 bij netto double bogey of slechter. 36 punten over 18 holes = precies je handicap gespeeld.",
  net: "Je bruto score min je playing handicap.",
  putts: "Aantal putts. Holes waar putts niet zijn bijgehouden tellen niet mee.",
  fairwayPct: "Hoe vaak je tee shot op de fairway landde, op par 4 en par 5 holes (par 3's tellen niet).",
  girPct: "Green in regulation: op de green liggen met nog minstens twee slagen voor par over (par 3 in 1, par 4 in 2, par 5 in 3).",
  scramblingPct: "Hoe vaak je nog par of beter maakte op holes waar je de green niet in regulation haalde.",
  penalties: "Strafslagen, bijvoorbeeld voor water, out of bounds of een onspeelbare bal.",
  bunker: "Aantal slagen vanuit een bunker.",
  threePutts: "Holes waarop je drie of meer keer putte.",
  puttsPerGir: "Gemiddeld aantal putts op holes waar je de green in regulation haalde. Zegt meer over je putten dan het totaal, omdat chips dicht bij de hole dat totaal flatteren.",
  distribution: "Hoe je scores per hole verdeeld zijn: eagle (−2), birdie (−1), par, bogey (+1), double bogey (+2) en slechter.",
  fairwayMiss: "Waar je tee shot terechtkwam als je de fairway miste.",
  fairwayRow: "● = fairway geraakt, ← links, → rechts, ↓ kort, ↑ lang. Op par 3's leeg.",
  frontBack: "Uit = holes 1–9, in = holes 10–18. Laat zien of je beter start of beter eindigt.",
  rolling: "Voortschrijdend gemiddelde: het gemiddelde van telkens de laatste 5 rondes. Laat de trend zien zonder de uitschieters.",
  keyFigures: "Je gemiddelde over de laatste 5 rondes (9-holes rondes omgerekend naar 18), vergeleken met de 5 rondes daarvoor.",
  records: "Je beste prestatie per baan. Minste putts telt alleen rondes waarin alle putts zijn bijgehouden.",
  parType: "Hoeveel slagen je gemiddeld boven par zit op par 3, par 4 en par 5 holes.",
  hardEasy: "Vergelijkt je score op de moeilijkste holes (laagste stroke index) met de rest.",
  blowUps: "Holes met een triple bogey (par + 3) of slechter. Vaak zit hier de meeste winst.",
  perHole: "Je gemiddelde per hole op één baan. De drie holes waar je het meest verliest zijn rood gemarkeerd.",
  source: "Hoe de ronde in de app kwam: via AI uit een screenshot of foto, handmatig ingevoerd of geïmporteerd uit CSV.",
  visibility: "Of vrienden met toegang deze ronde mogen zien. 'Volgens instelling' volgt je standaard bij Instellingen.",
  insights: "Automatisch gevonden patronen in je recente rondes, zoals een zwakke plek of een uitschieter.",

  // Strokes gained
  sg: "Strokes gained: hoeveel slagen je per categorie wint (+) of verliest (−) ten opzichte van een referentiespeler. Vereist slaginvoer per hole.",
  baseline: "Het niveau waarmee je wordt vergeleken. Kies een niveau net boven het jouwe om te zien waar je het meeste verliest.",
  offTheTee: "Tee shots op par 4 en par 5 holes.",
  approach: "Slagen naar de green van buiten 30 meter, inclusief de tee shot op par 3's.",
  aroundGreen: "Chips, pitches en bunkerslagen binnen 30 meter van de green.",
  putting: "Alle slagen op de green.",
  sgTotal: "Som van alle categorieën: hoeveel slagen je in totaal beter (+) of slechter (−) speelde dan de referentie.",
  clubDistance: "Gemiddelde afstand per club uit je slaginvoer. Spreiding: hoe groter, hoe minder constant.",
  lie: "Waar de bal lag vóór deze slag: tee, fairway, rough, bunker, green of strafgebied.",
  toFlag: "De afstand tot de vlag vóór deze slag. Hieruit berekent de app strokes gained.",

  // Instellingen
  gender: "Bepaalt welke course rating en slope van een tee voor jou gelden.",
  puttUnit: "In welke eenheid je putt-afstanden invoert.",
  sharing: "Standaard voor al je rondes: privé of zichtbaar voor spelers die je hebt uitgenodigd. Per ronde te overschrijven.",
  recalc: "Rekent de index, course en playing handicap en de punten van elke ronde opnieuw uit met de huidige rating, slope en instellingen (als eigenaar voor alle spelers). Gebeurt normaal automatisch; handig na een correctie buiten de app om.",
} as const;

export type GlossaryKey = keyof typeof GLOSSARY;
